### ISSUE TITLE
Some stuff that it would be great to add on.

### ISSUE THREAD

**Issue by Shipi1** [Mezy/PlayUHC-Community#7]
-An option that allow to be able to craft things in any order, like Vanilla Minecraft. In the current version of the plugin, the craft recipe can only be crafted in the way that the admin wrote on the config files.

Like:
 Air/Air/Air   
 Air/Air/GoldBlock    
Air/Air/Melon                   

That is the only way to craft that, and can not be like this: 
Air/Air/Air
Melon/GoldBlock/Air
Air/Air/Air

-Be able to use /tp like a normal server being an op.
-A option to use a map for ever. Ex: A map that you want to use always. And after ended an UHC, that map wont regenerate, just use the first version of that map, the version before being use on the UHC.
-Be able to change the name of the teams.

**Comment by Mezy** [comment]
Please leave suggestions in my discord: https://discord.gg/fDCaKMX
